# Generated by Django 3.1.4 on 2020-12-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20201218_1421'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='title')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='title',
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.basket', verbose_name='basket'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.supplier', verbose_name='supplier'),
        ),
    ]
