# Generated by Django 3.1.4 on 2020-12-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20201218_1838'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('basket__isnull', True), ('delta__gt', 0), ('supplier__isnull', False)), models.Q(('basket__isnull', False), ('delta__lt', 0), ('supplier__isnull', True)), _connector='OR'), name='mutual_exclusion'),
        ),
    ]
