# Generated by Django 3.1.4 on 2020-12-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='user',
        ),
        migrations.AddField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open - active basket'), ('Saved', 'Saved for later'), ('Submitted', 'Submitted - items has been purchased')], default='Open', max_length=15, verbose_name='Status'),
        ),
    ]
