# Generated by Django 3.1.6 on 2021-02-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('open', 'Open - active basket'), ('saved', 'Saved for later'), ('submitted', 'Submitted - items has been purchased')], default='Open', max_length=15, verbose_name='Status'),
        ),
    ]
