# Generated by Django 3.1.6 on 2021-03-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('basket', '0002_auto_20210302_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='basket.basket', verbose_name='basket lines')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Basket Line',
                'verbose_name_plural': 'Basket Lines',
            },
        ),
    ]
