# Generated by Django 3.1.4 on 2020-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='No description provided.', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('length', models.IntegerField(verbose_name='number of pages')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('book_format', models.CharField(choices=[('S', 'soft cover'), ('H', 'hard cover'), ('E', 'eBook')], max_length=1, verbose_name='book_format')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
