# Generated by Django 3.1.4 on 2021-01-01 05:02

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('description', models.TextField(blank=True, default='Description is not provided', verbose_name='description')),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('color', models.CharField(default='red', max_length=120)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hat_related', related_query_name='hat', to='catalog.category', verbose_name='related categories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbstractModelNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120, verbose_name="model's name")),
                ('app_label', models.CharField(max_length=120, verbose_name="application's label")),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.abstractmodelnode', verbose_name='parent')),
            ],
            options={
                'abstract': False,
                'unique_together': {('model_name', 'app_label')},
            },
        ),
    ]
