# Generated by Django 3.1.4 on 2021-01-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_abstractmodelnode_hat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractmodelnode',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='abstractmodelnode',
            name='mptt_level',
        ),
        migrations.RemoveField(
            model_name='abstractmodelnode',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='abstractmodelnode',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='abstractmodelnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.abstractmodelnode', verbose_name='parent'),
        ),
    ]
