# Generated by Django 3.1.4 on 2021-01-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210104_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractModelNode',
        ),
    ]
