# Generated by Django 3.1.4 on 2021-01-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_delete_abstractmodelnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120, verbose_name="model's name")),
                ('app_label', models.CharField(max_length=120, verbose_name="application's label")),
                ('lft', models.PositiveIntegerField(unique=True)),
                ('rgt', models.PositiveIntegerField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.modelnode', verbose_name='parent')),
            ],
            options={
                'abstract': False,
                'unique_together': {('model_name', 'app_label')},
            },
        ),
    ]
