# Generated by Django 3.1.4 on 2021-01-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_modelnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelnode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
