# Generated by Django 3.1.4 on 2021-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210115_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelnode',
            name='id',
        ),
        migrations.AlterField(
            model_name='modelnode',
            name='lft',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
