# Generated by Django 3.1.4 on 2021-01-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210115_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelnode',
            name='lft',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='left'),
        ),
        migrations.AlterField(
            model_name='modelnode',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.modelnode', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='modelnode',
            name='rgt',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='right'),
        ),
    ]
