# Generated by Django 3.1.4 on 2021-01-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210116_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelNode',
            new_name='ProductTree',
        ),
    ]
