# Generated by Django 3.1.4 on 2021-01-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210123_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTree',
            new_name='ProductTreeNode',
        ),
    ]
